// Generated by CoffeeScript 1.6.3
(function() {
  var FShared, compiledJS, exec, file, files, fs, importOrder, src;

  src = "" + __dirname + "/src/shared";

  compiledJS = "" + __dirname + "/functoids.js";

  fs = require('fs');

  exec = require('child_process').exec;

  FShared = require(src);

  importOrder = FShared._importOrder;

  files = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = importOrder.length; _i < _len; _i++) {
      file = importOrder[_i];
      _results.push("" + src + "/" + file + ".coffee");
    }
    return _results;
  })();

  console.log("Compiling: \n" + (files.join('\n')) + " to \n" + compiledJS);

  exec("coffee -cj " + compiledJS + " " + (files.join(' ')), function(err, stdout) {
    if (err != null) {
      throw new Error(err);
    }
  });

}).call(this);
